#!/usr/bin/env python3
"""
Replay CellReplay PDO traces via tc netem.
Expects a trace directory containing exactly:
  up-delay-light-pdo.txt   → propagation delay (column 2)
  down-delay-light-pdo.txt
  up-heavy-pdo.txt         → bandwidth schedule (timestamps)
  down-heavy-pdo.txt

Two delay modes:
  default      : fixed average delay from light PDO column 2
  --dist       : real delay distribution from .dist files
                 (generated by generate_netem_dist.py)

Usage:
  # Variant 1: fixed delay, 500ms window
  sudo python3 replay_trace.py --iface eth0 --trace-dir traces_new/v1 --window 500

  # Variant 2: fixed delay, 50ms window
  sudo python3 replay_trace.py --iface eth0 --trace-dir traces_new/v1 --window 50

  # Variant 3: real delay distribution, 50ms window
  #   First run: python3 generate_netem_dist.py --trace-dir traces_new/v1
  #   Then use the printed mean/jitter values below:
  sudo python3 replay_trace.py --iface eth0 --trace-dir traces_new/v1 \\
      --window 50 --dist \\
      --up-dist up_delay.dist --down-dist down_delay.dist \\
      --up-jitter <N> --down-jitter <N>
"""

import argparse
import os
import subprocess
import time
import sys
import signal
import statistics

WINDOW_MS = 500
BYTES_PER_PKT = 1500
MIN_RATE_KBPS = 10


# ── Trace parsing ──────────────────────────────────────────────────────────────


def parse_heavy(path):
    timestamps = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                timestamps.append(int(line))
    if not timestamps:
        raise ValueError(f"No timestamps in {path}")
    return sorted(timestamps)


def parse_delay_light(path):
    """Return (avg_delay_ms, all_delay_values)."""
    delays = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            vals = line.split()
            if len(vals) < 3:
                continue
            try:
                delays.append(int(vals[1]))
            except ValueError:
                continue
    if not delays:
        raise ValueError(f"No delay values in {path}")
    return int(statistics.mean(delays)), delays


def compute_bw_schedule(timestamps, window_ms):
    """O(n) linear scan instead of O(n²) nested loop."""
    t_start = timestamps[0]
    t_end = timestamps[-1]
    schedule = []

    i = 0
    n = len(timestamps)
    t = t_start

    while t < t_end:
        window_end = t + window_ms
        count = 0
        # advance pointer while timestamp falls in this window
        while i < n and timestamps[i] < window_end:
            count += 1
            i += 1
        kbps = max(MIN_RATE_KBPS, (count * BYTES_PER_PKT * 8) / window_ms)
        schedule.append((t - t_start, int(kbps)))
        t = window_end

    return schedule


# ── tc helpers ─────────────────────────────────────────────────────────────────


def run(cmd, check=True):
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if check and r.returncode != 0:
        if "already exists" not in r.stderr and "File exists" not in r.stderr:
            print(f"  [warn] {cmd!r} → {r.stderr.strip()}")
    return r


def netem_delay_str(delay_ms, use_dist, jitter_ms=None, dist_file=None):
    """Build the delay portion of a netem tc command."""
    if use_dist and dist_file and jitter_ms:
        return f"delay {delay_ms}ms {jitter_ms}ms distribution {dist_file}"
    else:
        return f"delay {delay_ms}ms"


def setup_egress(iface, delay_str, rate_kbps):
    run(f"tc qdisc del dev {iface} root 2>/dev/null", check=False)
    run(f"tc qdisc add dev {iface} root handle 1: netem " f"{delay_str} rate {rate_kbps}kbit")
    print(f"  Egress  (uplink)   on {iface}: {delay_str}  rate={rate_kbps} kbps")


def update_egress(iface, delay_str, rate_kbps):
    run(f"tc qdisc change dev {iface} root handle 1: netem " f"{delay_str} rate {rate_kbps}kbit")


def setup_ingress(iface, delay_str, rate_kbps):
    run("modprobe ifb", check=False)
    run("ip link add ifb0 type ifb 2>/dev/null", check=False)
    run("ip link set dev ifb0 up")
    run(f"tc qdisc del dev {iface} ingress 2>/dev/null", check=False)
    run(f"tc qdisc add dev {iface} handle ffff: ingress")
    run(
        f"tc filter add dev {iface} parent ffff: protocol ip u32 "
        f"match u32 0 0 action mirred egress redirect dev ifb0"
    )
    run("tc qdisc del dev ifb0 root 2>/dev/null", check=False)
    run(f"tc qdisc add dev ifb0 root handle 1: netem " f"{delay_str} rate {rate_kbps}kbit")
    print(f"  Ingress (downlink) on ifb0:   {delay_str}  rate={rate_kbps} kbps")


def update_ingress(delay_str, rate_kbps):
    run(f"tc qdisc change dev ifb0 root handle 1: netem " f"{delay_str} rate {rate_kbps}kbit")


def teardown(iface):
    print("\nCleaning up tc rules...")
    run(f"tc qdisc del dev {iface} root 2>/dev/null", check=False)
    run(f"tc qdisc del dev {iface} ingress 2>/dev/null", check=False)
    run(f"tc qdisc del dev ifb0 root 2>/dev/null", check=False)
    run("ip link set dev ifb0 down 2>/dev/null", check=False)
    run("ip link del ifb0 2>/dev/null", check=False)
    print("Done.")


# ── Main ───────────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(description="Replay CellReplay PDO traces via tc netem (3 variants)")
    # Required: 4-file interface matching mm-cellular
    parser.add_argument("--iface", required=True)
    parser.add_argument(
        "--trace-dir", required=True, help="Directory containing up/down light/heavy PDO .txt files"
    )

    # Bandwidth window
    parser.add_argument(
        "--window", type=int, default=WINDOW_MS, help=f"Bandwidth averaging window ms (default: {WINDOW_MS})"
    )

    # Delay distribution mode
    parser.add_argument(
        "--dist", action="store_true", help="Use real delay distribution instead of fixed delay"
    )
    parser.add_argument(
        "--up-jitter", type=int, default=None, help="Uplink jitter ms (printed by generate_netem_dist.py)"
    )
    parser.add_argument(
        "--down-jitter", type=int, default=None, help="Downlink jitter ms (printed by generate_netem_dist.py)"
    )
    args = parser.parse_args()

    # ── Resolve trace files from directory ──
    d = args.trace_dir
    up_light = os.path.join(d, "up-delay-light-pdo")
    down_light = os.path.join(d, "down-delay-light-pdo")
    up_heavy = os.path.join(d, "up-heavy-pdo")
    down_heavy = os.path.join(d, "down-heavy-pdo")
    up_dist = os.path.join(d, "up_delay.dist")
    down_dist = os.path.join(d, "down_delay.dist")
    for p in (up_light, down_light, up_heavy, down_heavy):
        if not os.path.isfile(p):
            print(f"ERROR: expected file not found: {p}")
            sys.exit(1)

    # ── Load traces ──
    print("\nLoading traces...")
    up_delay_ms, _ = parse_delay_light(up_light)
    down_delay_ms, _ = parse_delay_light(down_light)
    prop_delay_ms = max(up_delay_ms, down_delay_ms)

    print(f"  Up   prop delay (avg): {up_delay_ms} ms")
    print(f"  Down prop delay (avg): {down_delay_ms} ms")
    print(f"  Applied prop delay:    {prop_delay_ms} ms")

    up_ts = parse_heavy(up_heavy)
    down_ts = parse_heavy(down_heavy)
    print(f"  Up   heavy PDOs: {len(up_ts)}")
    print(f"  Down heavy PDOs: {len(down_ts)}")

    up_sched = compute_bw_schedule(up_ts, args.window)
    down_sched = compute_bw_schedule(down_ts, args.window)
    avg_up = sum(r for _, r in up_sched) // len(up_sched)
    avg_down = sum(r for _, r in down_sched) // len(down_sched)
    print(f"\n  Uplink schedule:   {len(up_sched)} windows, avg {avg_up} kbps")
    print(f"  Downlink schedule: {len(down_sched)} windows, avg {avg_down} kbps")

    # ── Delay mode ──
    if args.dist:
        if args.up_jitter is None or args.down_jitter is None:
            print("\nERROR: --dist requires --up-jitter and --down-jitter")
            print("Run generate_netem_dist.py first to get these values.")
            sys.exit(1)
        up_delay_str = netem_delay_str(prop_delay_ms, True, args.up_jitter, up_dist)
        down_delay_str = netem_delay_str(prop_delay_ms, True, args.down_jitter, down_dist)
        print(f"\n  Delay mode: DISTRIBUTION")
        print(f"    Up:   {up_delay_str}")
        print(f"    Down: {down_delay_str}")
    else:
        up_delay_str = netem_delay_str(prop_delay_ms, False)
        down_delay_str = netem_delay_str(prop_delay_ms, False)
        print(f"\n  Delay mode: FIXED ({prop_delay_ms}ms)")

    # ── Setup tc ──
    variant = f"dist+{args.window}ms" if args.dist else f"fixed+{args.window}ms"
    print(f"\nSetting up tc netem on {args.iface}  [variant: {variant}]...")
    setup_egress(args.iface, up_delay_str, up_sched[0][1])
    setup_ingress(args.iface, down_delay_str, down_sched[0][1])

    def on_exit(sig, frame):
        teardown(args.iface)
        sys.exit(0)

    signal.signal(signal.SIGINT, on_exit)
    signal.signal(signal.SIGTERM, on_exit)

    # ── Replay loop ──
    print(f"\nReplaying ({args.window}ms windows)... Ctrl+C to stop.\n")
    up_i = down_i = 0
    start = time.time()

    while up_i < len(up_sched) or down_i < len(down_sched):
        elapsed_ms = (time.time() - start) * 1000
        up_changed = down_changed = False

        if up_i < len(up_sched) and elapsed_ms >= up_sched[up_i][0]:
            up_rate = up_sched[up_i][1]
            update_egress(args.iface, up_delay_str, up_rate)
            up_i += 1
            up_changed = True
        else:
            up_rate = up_sched[up_i - 1][1] if up_i > 0 else up_sched[0][1]

        if down_i < len(down_sched) and elapsed_ms >= down_sched[down_i][0]:
            down_rate = down_sched[down_i][1]
            update_ingress(down_delay_str, down_rate)
            down_i += 1
            down_changed = True
        else:
            down_rate = down_sched[down_i - 1][1] if down_i > 0 else down_sched[0][1]

        if up_changed or down_changed:
            mu = "*" if up_changed else " "
            md = "*" if down_changed else " "
            print(
                f"  t={elapsed_ms/1000:6.2f}s  " f"UP{mu}={up_rate:6d} kbps  " f"DOWN{md}={down_rate:6d} kbps"
            )

        time.sleep(args.window / 1000)

    teardown(args.iface)


if __name__ == "__main__":
    if __import__("os").geteuid() != 0:
        print("Error: must run as root (sudo)")
        sys.exit(1)
    main()
